// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('LoginTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LoginTest', async function() {
    // Test name: LoginTest
    // Step # | name | target | value
    // 1 | open | http://localhost:3000/login | 
    await driver.get("http://localhost:3000/login")
    // 2 | setWindowSize | 808x824 | 
    await driver.manage().window().setRect(808, 824)
    // 3 | click | css=.role > .form-control | 
    await driver.findElement(By.css(".role > .form-control")).click()
    // 4 | select | css=.role > .form-control | label=Farmer
    {
      const dropdown = await driver.findElement(By.css(".role > .form-control"))
      await dropdown.findElement(By.xpath("//option[. = 'Farmer']")).click()
    }
    // 5 | click | css=.email > .form-control | 
    await driver.findElement(By.css(".email > .form-control")).click()
    // 6 | type | css=.email > .form-control | ameshawahalathanthri20@gmail.com
    await driver.findElement(By.css(".email > .form-control")).sendKeys("ameshawahalathanthri20@gmail.com")
    // 7 | click | css=.password > .form-control | 
    await driver.findElement(By.css(".password > .form-control")).click()
    // 8 | type | css=.password > .form-control | 123456
    await driver.findElement(By.css(".password > .form-control")).sendKeys("123456")
    // 9 | click | id=customCheck1 | 
    await driver.findElement(By.id("customCheck1")).click()
    // 10 | click | css=.login-button | 
    await driver.findElement(By.css(".login-button")).click()
  })
})
